# Generated by Django 2.2.6 on 2019-11-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_game', models.DateField(auto_now=True)),
                ('status_game', models.CharField(max_length=5)),
                ('letters_b', models.CharField(max_length=100, null=True)),
                ('letters_i', models.CharField(max_length=100, null=True)),
                ('letters_n', models.CharField(max_length=100, null=True)),
                ('letters_g', models.CharField(max_length=100, null=True)),
                ('letters_o', models.CharField(max_length=100, null=True)),
                ('winner', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
