name: Lint
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
jobs:
  lint:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Open Project-Bingo
        run: |
          cd Project-Bingo
      - uses: psf/black@stable