name: Tests
on: [push]
jobs:
  lint:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Black Formatter Check
        uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: ./Project-Bingo
  test-py:
    name: Python Tests (3.8)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show Python environment
        run: |
          python --version
          python -m pip list
      - name: Run Python tests
        run: |
          cd Project-Bingo
          coverage run --source=. -m unittest discover -v -s tests/ -p "*_test.py"
          coverage report -m --omit=tests/*,*__init__.py
